name: format

on:
  push:
    branches: ["main"]
    
jobs:
  lint-changelog:
    name: Lint changelog file
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Lint files
      uses: docker://avtodev/markdown-lint:v1 # fastest way
      with:    
        args: '**/*.md --fix'
        

